#!/usr/bin/env python3

import argparse
import os.path
import sys
import libkiara

parser = argparse.ArgumentParser(
	description='Do stuff with anime files and anidb.')
parser.add_argument('-w', '--watch',
	action='store_true', dest='watch',
	help='Mark all the files watched.')
parser.add_argument('-o', '--organize',
	action='store_true', dest='organize',
	help='Organize ALL THE FILES _o/')
parser.add_argument('--copy',
	action='store_true', dest='organize_copy',
	help='When organizing files, copy them instead of moving them.')
parser.add_argument('--overwrite',
	action='store_true', dest='organize_overwrite',
	help='When organizing files, always overwrite any existing files.')
parser.add_argument('--skip-update',
	action='store_false', dest='update_info', default=True,
	help='Skip updating file info from anidb, when the cached info is old. '
		'(missing info will still be fetched)')
parser.add_argument('-c', '--config',
	action='store', dest='config', type=argparse.FileType('r'),
	help='Alternative config file to use.')
parser.add_argument('--find-duplicates',
	action='store_true', dest='find_duplicates',
	help='Lists all episode for which you have more than one file')
parser.add_argument('--forget',
	type=int, metavar='FID', nargs='*', dest='forget_fid',
	help='Delete all info from the database (but not the file itself) about '
		'the files with the giver anidb file-id. (These are the numbers output '
		'by --find-duplicates')
parser.add_argument('file',
	metavar='FILE', type=str, nargs='*',
	help='A file to do something with')

args = parser.parse_args()

# First, make sure that all the files are actually files.
for file in args.file:
	if not os.path.isfile(os.path.abspath(file)):
		print('!!! %s is not a file' % file)
		sys.exit()

if args.config:
	libkiara.load_config_file(args.config.name)
if not libkiara.check_config():
	sys.exit(-1)

assert libkiara.ping()

# OK, run over the files.
for file in args.file:
	libkiara.process(os.path.abspath(file),
			update_info=args.update_info,
			watch=args.watch,
			organize=args.organize,
			organize_copy=args.organize_copy,
			organize_overwrite=args.organize_overwrite)
if args.find_duplicates:
	print('Locating duplicate files...')
	libkiara.find_duplicates()
if args.forget_fid:
	libkiara.forget(*args.forget_fid)
